# Generated by Django 3.1.1 on 2020-12-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_proyecto_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
